# Generated by Django 5.1.7 on 2025-05-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='diretor_aprovacao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='rh_dp_aprovacao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='upload_gestor',
            field=models.ImageField(blank=True, null=True, upload_to='registros'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('gestor', 'Gestor'), ('diretor', 'Diretor'), ('rh_dp', 'RH/DP'), ('sesmt', 'Sesmt')], max_length=10, null=True),
        ),
    ]
