# Generated by Django 5.1.7 on 2025-07-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='relatorio_gestor',
            field=models.FileField(blank=True, null=True, upload_to='registros/relatorio'),
        ),
    ]
