# Generated by Django 5.1.7 on 2025-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='areas_operacionais_com_risco',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='data1',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='numero_chamado',
            new_name='n_chamado',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='nome1',
        ),
        migrations.AddField(
            model_name='chamado',
            name='aso',
            field=models.CharField(choices=[('Apto', 'Apto'), ('Não Apto', 'Não Apto'), ('Não Aplicável', 'Não Aplicável')], default='Não Aplicável', max_length=20),
        ),
        migrations.AddField(
            model_name='chamado',
            name='data6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='nome6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='treinamentoa',
            field=models.CharField(choices=[('Apto', 'Apto'), ('Não Apto', 'Não Apto'), ('Não Aplicável', 'Não Aplicável')], default='Não Aplicável', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='frequencia',
            field=models.CharField(max_length=50),
        ),
    ]
