# Generated by Django 5.1.7 on 2025-05-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_chamado_diretor_aprovacao_chamado_rh_dp_aprovacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='data2',
            new_name='data_autorizacao_gestor',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='data3',
            new_name='data_autorizacao_rh_dp',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='data4',
            new_name='data_autorizacao_sesmt',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='laudo',
            new_name='locais_atuaçao',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='credenciado_a',
            new_name='nome_colaborador',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='area_risco',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='autorizacao',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='data',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='data5',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='data6',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='n_chamado',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='nome2',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='nome3',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='nome4',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='nome5',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='nome6',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='rh_dp_aprovacao',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='treinamentoa',
        ),
        migrations.AddField(
            model_name='chamado',
            name='aso_descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='assinatura_gestor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/chamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='assinatura_rh_dp',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh_dp/chamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='assinatura_sesmt',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/sesmt/chamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='curso_nr10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='curso_nr35',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='curso_sep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='cursos_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='descricao_atividades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='epi_epc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='epi_epc_descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='gestor_imediato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='natureza_risco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='nome_rh_dp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='nome_sesmt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='outro_natureza_risco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='procedimento_rh_dp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo_exposicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='aso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='atividade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='depto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='frequencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
