# Generated by Django 5.1.7 on 2025-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_rename_areas_operacionais_com_risco_chamado_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='area_risco',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AddField(
            model_name='chamado',
            name='laudo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
