# Generated by Django 5.1.7 on 2025-07-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_chamado_relatorio_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadobackup',
            name='relatorio_gestor',
            field=models.FileField(blank=True, null=True, upload_to='registros/relatorio'),
        ),
    ]
