# Generated by Django 5.1.7 on 2025-03-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_chamado_area_risco_chamado_laudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='nao_registrado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo_parecer',
            field=models.CharField(choices=[('Eventual', 'Eventual'), ('Intermitente', 'Intermitente'), ('Permanente', 'Permanente'), ('Sem Exposição', 'Sem Exposição')], default='Sem Exposição', max_length=20),
        ),
    ]
