# Generated by Django 5.1.7 on 2025-05-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_rename_data2_chamado_data_autorizacao_gestor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='aso_descricao',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_gestor',
            field=models.ImageField(upload_to='assinaturas/gestor/chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_rh_dp',
            field=models.ImageField(upload_to='assinaturas/rh_dp/chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_sesmt',
            field=models.ImageField(upload_to='assinaturas/sesmt/chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='atividade',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_autorizacao_gestor',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_autorizacao_rh_dp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_autorizacao_sesmt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='depto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='descricao_atividades',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='frequencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='funcao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='gestor_imediato',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='locais_atuaçao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='natureza_risco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='nome_colaborador',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='outro_natureza_risco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='responsavel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tipo_exposicao',
            field=models.CharField(max_length=100),
        ),
    ]
