# Generated by Django 5.1.7 on 2025-03-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_chamado_nao_registrado_chamado_tipo_parecer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='autorizacao',
            field=models.CharField(choices=[('Nao Autorizado', 'Não Autorizado'), ('Autorizado', 'Autorizado')], default='Nao Autorizado', max_length=20),
        ),
        migrations.AddField(
            model_name='chamado',
            name='credenciado_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
