# Generated by Django 5.1.7 on 2025-05-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_alter_chamado_aso_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_autorizacao_rh_dp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
