# Generated by Django 5.1.7 on 2025-05-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alter_chamado_data_autorizacao_rh_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_autorizacao_sesmt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
