# Generated by Django 5.1.7 on 2025-03-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_chamado_autorizacao_chamado_credenciado_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='nao_registrado',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='tipo_parecer',
        ),
    ]
