# Generated by Django 5.1.7 on 2025-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_alter_chamado_data_autorizacao_sesmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_gestor',
            field=models.ImageField(upload_to='assinaturas/gestor/chamado/'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='outro_natureza_risco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
