# Generated by Django 5.1.7 on 2025-05-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_alter_chamado_assinatura_gestor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_gestor',
            field=models.ImageField(upload_to='assinaturas/gestor/chamado'),
        ),
    ]
