# Generated by Django 5.1.7 on 2025-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_alter_chamado_assinatura_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='upload_gestor',
            field=models.FileField(blank=True, null=True, upload_to='registros'),
        ),
    ]
