# Generated by Django 5.1.7 on 2025-06-02 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0009_alter_chamado_upload_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='usuario_gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='upload_gestor',
            field=models.FileField(blank=True, null=True, upload_to='registros/uploads'),
        ),
    ]
