# Generated by Django 5.1.7 on 2025-06-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0010_chamado_usuario_gestor_alter_chamado_upload_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='aso_documento',
            field=models.FileField(blank=True, null=True, upload_to='registros/uploads'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='curso_nr10_documento',
            field=models.FileField(blank=True, null=True, upload_to='registros/uploads'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='curso_nr35_documento',
            field=models.FileField(blank=True, null=True, upload_to='registros/uploads'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='curso_sep_documento',
            field=models.FileField(blank=True, null=True, upload_to='registros/uploads'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='epi_epc_documento',
            field=models.FileField(blank=True, null=True, upload_to='registros/uploads'),
        ),
    ]
