# Generated by Django 5.1.7 on 2025-06-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0011_chamado_aso_documento_chamado_curso_nr10_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='assinatura_diretor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/diretor/chamado'),
        ),
    ]
