# Generated by Django 5.1.7 on 2025-06-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0012_chamado_assinatura_diretor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='diretor_aprovacao',
        ),
    ]
