# Generated by Django 5.1.7 on 2025-06-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0013_remove_chamado_diretor_aprovacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='outro_natureza_risco',
        ),
    ]
