# Generated by Django 5.1.7 on 2025-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0014_remove_chamado_outro_natureza_risco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='natureza_risco',
            field=models.CharField(max_length=255),
        ),
    ]
