# Generated by Django 5.1.7 on 2025-06-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0016_chamado_diretor_aprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='gestor_ciente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='rh_dp_ciente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='sesmt_ciente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
