# Generated by Django 5.1.7 on 2025-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0017_chamado_gestor_ciente_chamado_rh_dp_ciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_rh_dp',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh_dp/chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_sesmt',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/sesmt/chamado'),
        ),
    ]
