# Generated by Django 5.1.7 on 2025-06-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0018_alter_chamado_assinatura_rh_dp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='upload_gestor',
            new_name='upload_gpm',
        ),
    ]
