# Generated by Django 5.1.7 on 2025-07-08 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0019_rename_upload_gestor_chamado_upload_gpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_autorizacao_diretor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='imagem_assinatura_diretor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/diretor/chamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='imagem_assinatura_gestor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/chamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='imagem_assinatura_rh_dp',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh_dp/chamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='imagem_assinatura_sesmt',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/sesmt/chamado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_diretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_assinados_como_diretor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_assinados_como_gestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_rh_dp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_assinados_como_rh_dp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='assinatura_sesmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_assinados_como_sesmt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_autorizacao_gestor',
            field=models.DateField(blank=True, null=True),
        ),
    ]
