# Generated by Django 5.1.7 on 2025-07-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0020_chamado_data_autorizacao_diretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
