# Generated by Django 5.1.7 on 2025-07-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0021_customuser_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='atividade',
        ),
    ]
