# Generated by Django 5.1.7 on 2025-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0022_remove_chamado_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='frequencia',
            field=models.CharField(default='16/06 - 15/07.', max_length=50),
        ),
    ]
