# Generated by Django 5.1.7 on 2025-07-18 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0023_alter_chamado_frequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('gestor', 'Gestor'), ('diretor', 'Diretor/Gerente'), ('rh_dp', 'RH/DP'), ('sesmt', 'Sesmt')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ChamadoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_colaborador', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=50)),
                ('funcao', models.CharField(max_length=100)),
                ('depto', models.CharField(max_length=100)),
                ('gestor_imediato', models.CharField(max_length=100)),
                ('tipo_exposicao', models.CharField(max_length=100)),
                ('natureza_risco', models.CharField(max_length=255)),
                ('descricao_atividades', models.TextField()),
                ('locais_atuaçao', models.CharField(max_length=255)),
                ('frequencia', models.CharField(default='16/06 - 15/07.', max_length=50)),
                ('responsavel', models.CharField(max_length=100)),
                ('data_autorizacao_gestor', models.DateField(blank=True, null=True)),
                ('imagem_assinatura_gestor', models.ImageField(blank=True, null=True, upload_to='assinaturas/backup/gestor/chamado')),
                ('diretor_aprovacao', models.BooleanField(blank=True, null=True)),
                ('data_autorizacao_diretor', models.DateTimeField(blank=True, null=True)),
                ('imagem_assinatura_diretor', models.ImageField(blank=True, null=True, upload_to='assinaturas/backup/diretor/chamado')),
                ('aso', models.CharField(blank=True, max_length=100, null=True)),
                ('aso_documento', models.FileField(blank=True, null=True, upload_to='backup/uploads')),
                ('aso_descricao', models.TextField(blank=True, max_length=100, null=True)),
                ('epi_epc', models.CharField(blank=True, max_length=100, null=True)),
                ('epi_epc_documento', models.FileField(blank=True, null=True, upload_to='backup/uploads')),
                ('epi_epc_descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('curso_nr10', models.CharField(blank=True, max_length=100, null=True)),
                ('curso_nr10_documento', models.FileField(blank=True, null=True, upload_to='backup/uploads')),
                ('curso_sep', models.CharField(blank=True, max_length=100, null=True)),
                ('curso_sep_documento', models.FileField(blank=True, null=True, upload_to='backup/uploads')),
                ('curso_nr35', models.CharField(blank=True, max_length=100, null=True)),
                ('curso_nr35_documento', models.FileField(blank=True, null=True, upload_to='backup/uploads')),
                ('cursos_observacoes', models.TextField(blank=True, null=True)),
                ('data_autorizacao_sesmt', models.DateField(blank=True, null=True)),
                ('nome_sesmt', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem_assinatura_sesmt', models.ImageField(blank=True, null=True, upload_to='assinaturas/backup/sesmt/chamado')),
                ('upload_gpm', models.FileField(blank=True, null=True, upload_to='backup/uploads')),
                ('procedimento_rh_dp', models.CharField(blank=True, max_length=100, null=True)),
                ('data_autorizacao_rh_dp', models.DateField(blank=True, null=True)),
                ('nome_rh_dp', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem_assinatura_rh_dp', models.ImageField(blank=True, null=True, upload_to='assinaturas/backup/rh_dp/chamado')),
                ('gestor_ciente', models.BooleanField(blank=True, default=False, null=True)),
                ('sesmt_ciente', models.BooleanField(blank=True, default=False, null=True)),
                ('rh_dp_ciente', models.BooleanField(blank=True, default=False, null=True)),
                ('data_exclusao', models.DateTimeField(auto_now_add=True)),
                ('assinatura_diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_assinados_como_diretor', to=settings.AUTH_USER_MODEL)),
                ('assinatura_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_assinados_como_gestor', to=settings.AUTH_USER_MODEL)),
                ('assinatura_rh_dp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_assinados_como_rh_dp', to=settings.AUTH_USER_MODEL)),
                ('assinatura_sesmt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_assinados_como_sesmt', to=settings.AUTH_USER_MODEL)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_excluidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
