# Generated by Django 5.1.7 on 2025-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0024_alter_customuser_role_chamadobackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadobackup',
            name='motivo_exclusao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
